// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdYV9utjN0a0j0vUY9MNOvfbOFliz9p90',
    appId: '1:952930504682:web:af4fc47ac6d9ce7ae32c93',
    messagingSenderId: '952930504682',
    projectId: 'zest-employee',
    authDomain: 'zest-employee.firebaseapp.com',
    storageBucket: 'zest-employee.firebasestorage.app',
    measurementId: 'G-WW3PC0N5KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD18vcM0Me7zgPBjGei8l4aSC1QmHaYV3A',
    appId: '1:952930504682:android:9dbc40537a700b79e32c93',
    messagingSenderId: '952930504682',
    projectId: 'zest-employee',
    storageBucket: 'zest-employee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3U0AJ7h0sgYnVlwPm_xCAdZyxh6P1Oug',
    appId: '1:952930504682:ios:269415c09dc7673de32c93',
    messagingSenderId: '952930504682',
    projectId: 'zest-employee',
    storageBucket: 'zest-employee.firebasestorage.app',
    iosBundleId: 'com.zestEmployee.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3U0AJ7h0sgYnVlwPm_xCAdZyxh6P1Oug',
    appId: '1:952930504682:ios:269415c09dc7673de32c93',
    messagingSenderId: '952930504682',
    projectId: 'zest-employee',
    storageBucket: 'zest-employee.firebasestorage.app',
    iosBundleId: 'com.zestEmployee.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdYV9utjN0a0j0vUY9MNOvfbOFliz9p90',
    appId: '1:952930504682:web:320d058828a4910ae32c93',
    messagingSenderId: '952930504682',
    projectId: 'zest-employee',
    authDomain: 'zest-employee.firebaseapp.com',
    storageBucket: 'zest-employee.firebasestorage.app',
    measurementId: 'G-K3ZG1EZMCQ',
  );
}
